import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import IsAbleToShow from "@/components/is-able-to-show";

const poppins = Poppins({
  variable: "--poppins-font",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${poppins.className} antialiased bg-background`}
      >
        <IsAbleToShow>
          <div>
            {children}
          </div>
        </IsAbleToShow>
      </body>
    </html>
  );
}
